### ISSUE TITLE
point codalab.fragilefamilieschallenge.org to 

### ISSUE THREAD

**Issue by msalganik** [fragilefamilieschallenge/codalab-competitions#18]
the challenge page that @ilundberg  made:

13.82.221.77/competitions/17

In other words, when people go to codalab.fragilefamilieschallenge.org they should be redirected to 13.82.221.77/competitions/17

**Comment by lukebaker** [comment]
I've updated the default competition to be that one, so when you visit codalab.fragilefamilieschallenge.org, you should see that one. Secondly, I updated the server configuration so that if someone visits with the IP then they get redirected to the same URL on codalab.fragilefamilieschallenge.org. This may require folks to log in again.

**Comment by msalganik** [comment]
Awesome.  Thanks Luke.
