### ISSUE TITLE
update testing data to be the same size as the real data

### ISSUE THREAD

**Issue by msalganik** [fragilefamilieschallenge/codalab-competitions#4]
@ilundberg 

Pretty soon we are going to start load testing FFC Codalab.  To do that, we need fake scoreboard data that is the same size as we will use in the real challenge.  My understanding is that what we are using for testing now is much smaller.  So please create fake scoreboard data that is the same size as the real scoreboard data.

Let me know if you have any questions (or if the fake scoreboard data is already the right size).

**Comment by ilundberg** [comment]
@msalganik The Codalab scoreboard data is part of the individual competition I create. I'm inclined to create the actual file early next week, incorporating our text revisions as well as the real data. To accomplish that, I just need to get a file from Kate and we need to finalize the text. That seems better because we won't have to test twice - once on fake data and once on real data - we can just go straight to the real version. Does that seem right? Or are there scientific or workload reasons to prefer simulated data first?

**Comment by msalganik** [comment]
@ilundberg I'm try to keep things organized on github.  I believe that you have already uploaded real sized fake data to FFC CodaLab.  If that is right, please mark this issue "closed".  Thanks.

**Comment by ilundberg** [comment]
Yes, this is done and tested. Thanks for the reminder.
