### ISSUE TITLE
architecture overview

### ISSUE THREAD

**Issue by msalganik** [fragilefamilieschallenge/codalab-competitions#5]
@ckcollab 

In order to prepare for load testing it would be helpful to have an overview of the architecture and where you think the bottlenecks might be.  I could not find anything like that on the main codalab docs (sorry if I missed it).  Could you write up something like that?  If you think it would be helpful to others, please add it to the main codalab docs.

**Comment by ckcollab** [comment]
Not sure how helpful this would be in the Wiki, especially since we plan on replacing all of these docs sooner than later. Here's a quick overview of the architecture, from my memory:

1. nginx is the first layer receiving the request, if there is a bottleneck on certain pages you could implement caching here
2. uwsgi receives request and processes request, here you could access caching via memcached or `django-layered-caching` could also be helpful (I helped modify that for another project)
3. django will talk with mysql during request, maybe connection pooling could alleviate bottlenecks here?
4. django will put a message on service bus queue sometimes for site worker OR compute worker
5. service bus seems to scale just fine, not sure of optimizations that could be done here
6. Site worker builds competitions and processes submission updates, shouldn't have problems here ever but you could run more site workers
7. Compute worker evaluates submissions and returns updates to site worker, again you could potentially run more compute workers to scale

Also, could setup New Relic to help find hot spots in the request/response cycle.

Just quickly jotted that down, hope it's helpful! May be missing a chunk or two.

**Comment by msalganik** [comment]
Thanks @ckcollab 

If you think this is not helpful on the wiki, that's fine.  No need to do that.

@lukebaker do you have what you need?  If so, please close this issue.

**Comment by lukebaker** [comment]
Thanks @ckcollab.

> Site worker builds competitions and processes submission updates, shouldn't have problems here ever but you could run more site workers
> Compute worker evaluates submissions and returns updates to site worker, again you could potentially run more compute workers to scale

Can you help me understand what you mean by "processes submission updates" versus what happens in the computer worker?

**Comment by ckcollab** [comment]
Luke,

No problem!

So, the compute worker isn't connected to the database at all -- all the
compute worker should be worried about is grabbing submissions from Azure
Storage, running them, and returning output.

The site worker is connected to the database and handles submission
updates/statuses to display to the user. The compute worker relays these
updates back to the site worker throughout the processing of a submission.

Hope that makes sense, thanks,
Eric

(whoops! didn't notice this was an issue, thought it was an email convo)

**Comment by lukebaker** [comment]
> The site worker is connected to the database and handles submission
> updates/statuses to display to the user. The compute worker relays these
> updates back to the site worker throughout the processing of a submission.

Is it accurate to say that the site worker isn't very computationally intensive, while the compute worker may be computationally intensive. In other words, it may be possible that we'd need to add additional compute workers, but unlikely that we'd need to add additional site workers?

**Comment by ckcollab** [comment]
Yep, site-workers don't do much heavy lifting. Compute workers are what you'd probably want to scale.

**Comment by msalganik** [comment]
Thanks @ckcollab 

This is very helpful.  I'm closing this issue now.
