### ISSUE TITLE
back-end modifications?

### ISSUE THREAD

**Issue by msalganik** [fragilefamilieschallenge/codalab-competitions#8]
@ckcollab 

As we move from a multi-challenge site to a single-challenge site are there any changes we need to make to the back-end?

For example, in allourideas there are certain things used to be hard-coded to "phoned-home" to us, but which really should have "phoned-home" to the new owner.  Is there anything like that in CodaLab?  

I'm looping @lukebaker into this thread because he's been through this a few times with allourideas.

**Comment by ckcollab** [comment]
I think it might be a good idea to hide some links, for example there's no need to Search Competitions. This behavior could be rolled into the "single competition landing page" feature, modifying the front end to be based around one competition instead of many. May help with Codalab's confusing interface.

Otherwise, I don't think any changes *need* to be made like some hardcoded codalab.org values... there may be some. For example, some emails may say "from the Codalab team", but the links should be relatively to the `Site` model.

**Comment by msalganik** [comment]
@ckcollab 

I like the idea of "single competition landing page".  That sounds right to me.  Please go ahead with that.

**Comment by ckcollab** [comment]
Note: this is related to and probably can be closed by #3

**Comment by msalganik** [comment]
@ckcollab Is there anything hard-coded into the back end that phones home to codalab?  For example, with allourideas, we used to unintentionally get bug reports from new instances of the site because our address was hard coded.

**Comment by ckcollab** [comment]
I don't believe so, the codebase has gone through many hands and I just took it back up recently so something new could be added I'm not aware of I suppose. New Relic comes to mind, but that's a configuration setting so not hard coded I don't think.

**Comment by msalganik** [comment]
OK, sounds good.  I'm closing this issue.  Thanks.
